CREATE USER 'username'@'hostname' IDENTIFIED BY 'password';
#PASSWORD EXPIRE
CREATE USER 'jeffrey'@'localhost' PASSWORD EXPIRE;
#PASSWORD EXPIRE INTERVAL N DAY
CREATE USER 'jeffrey'@'localhost' PASSWORD EXPIRE INTERVAL 180 DAY;
#PASSWORD EXPIRE NEVER
CREATE USER 'jeffrey'@'localhost' PASSWORD EXPIRE NEVER;
#PASSWORD EXPIRE DEFAULT
CREATE USER 'jeffrey'@'localhost' PASSWORD EXPIRE DEFAULT;

